use via_core::FootprintPads;
use via_footprint_ir::{FootprintIr, TextKind};

use crate::epru::EpruWriter;
use crate::footprint_records::{FootprintLineRecord, FootprintPadRecord, FootprintTextRecord};
use crate::ids::{footprint_uuid, json_escape};
use crate::layers::{render_layer_phys, render_standard_layers};

pub(crate) fn render_footprint_document(writer: &mut EpruWriter, footprint: &FootprintPads) {
    writer.dochead("FOOTPRINT", &footprint_uuid(footprint.name()));
    writer.record_with_id(
        "CANVAS",
        "CANVAS",
        concat!(
            "{\"originX\":0,\"originY\":0,\"unit\":\"mil\",",
            "\"gridXSize\":10,\"gridYSize\":10,",
            "\"snapXSize\":1,\"snapYSize\":1,",
            "\"altSnapXSize\":1,\"altSnapYSize\":1,",
            "\"gridType\":\"GRID\",\"multiGridType\":\"GRID\",",
            "\"multiGridRatio\":5,\"highlightValue\":0.6}"
        ),
    );
    render_standard_layers(writer);
    writer.record_with_id("ACTIVE_LAYER", "ACTIVE_LAYER", "{\"layerId\":1}");
    if let Some(ir) = footprint.ir() {
        render_footprint_ir_geometry(writer, ir);
    } else {
        render_fallback_footprint_pads(writer, footprint);
    }

    writer.record_with_id(
        "META",
        "META",
        &format!(
            "{{\"title\":\"{}\",\"description\":\"Generated by via; verify physical dimensions before fabrication\",\"tags\":[\"via\"]}}",
            json_escape(footprint.name()),
        ),
    );
    render_layer_phys(writer);
    writer.record_with_id(
        "NET",
        "[\"NET\",\"\"]",
        "{\"netType\":null,\"specialColor\":null,\"retLine\":true,\"differentialName\":null,\"isPositiveNet\":false,\"equalLengthGroupName\":null}",
    );
}

fn render_footprint_ir_geometry(writer: &mut EpruWriter, footprint: &FootprintIr) {
    writer.record_with_id(
        "ELE_PLACEHOLDER",
        "placeholder_pads",
        &format!(
            "{{\"dataType\":\"PAD\",\"max\":{}}}",
            footprint.pads().len()
        ),
    );
    for (index, pad) in footprint.pads().iter().enumerate() {
        FootprintPadRecord::from_ir(pad, 100 + index).write(writer);
    }

    if !footprint.lines().is_empty() {
        writer.record_with_id(
            "ELE_PLACEHOLDER",
            "placeholder_lines",
            &format!(
                "{{\"dataType\":\"LINE\",\"max\":{}}}",
                footprint.lines().len()
            ),
        );
    }
    for (index, line) in footprint.lines().iter().enumerate() {
        FootprintLineRecord::from_ir(line, 300 + index).write(writer);
    }

    let texts = footprint
        .texts()
        .iter()
        .filter(|text| matches!(text.kind, TextKind::User))
        .collect::<Vec<_>>();
    if !texts.is_empty() {
        writer.record_with_id(
            "ELE_PLACEHOLDER",
            "placeholder_strings",
            &format!("{{\"dataType\":\"STRING\",\"max\":{}}}", texts.len()),
        );
    }
    for (index, text) in texts.iter().enumerate() {
        FootprintTextRecord::from_ir(text, 500 + index).write(writer);
    }
}

fn render_fallback_footprint_pads(writer: &mut EpruWriter, footprint: &FootprintPads) {
    writer.record_with_id(
        "ELE_PLACEHOLDER",
        "placeholder_pads",
        &format!(
            "{{\"dataType\":\"PAD\",\"max\":{}}}",
            footprint.pads().len()
        ),
    );

    let pads = footprint.pads().iter().collect::<Vec<_>>();
    let columns = pads.len().clamp(1, 16);
    let origin_x = -((columns as f64 - 1.0) * 50.0);
    for (index, pad) in pads.iter().enumerate() {
        let pad_name = pad.as_str();
        let col = index % columns;
        let row = index / columns;
        let x = origin_x + col as f64 * 100.0;
        let y = row as f64 * 100.0;
        FootprintPadRecord::placeholder(pad_name, x, y, 100 + index).write(writer);
    }
}
