use std::collections::BTreeMap;

use via_core::{Board, SymbolSide};

use super::model::{PlacedModule, SymbolPin, SymbolTemplate};
use super::util::{escape, fmt_num, sanitize_symbol, stable_uuid};
use super::{
    BODY_HALF_WIDTH, GENERATOR, LABEL_STUB, PIN_LENGTH, SCHEMATIC_VERSION, SYMBOL_LIB_VERSION,
    SchematicProjectOptions,
};

pub(super) fn render_schematic(
    board: &Board,
    options: &SchematicProjectOptions,
    templates: &BTreeMap<String, SymbolTemplate>,
    placed: &[PlacedModule],
    pin_nets: &BTreeMap<(String, String), String>,
) -> String {
    let sheet_uuid = stable_uuid(&format!("sheet:{}", board.name()));
    let mut out = String::new();

    out.push_str("(kicad_sch\n");
    out.push_str(&format!("  (version {SCHEMATIC_VERSION})\n"));
    out.push_str(&format!("  (generator \"{GENERATOR}\")\n"));
    out.push_str(&format!(
        "  (generator_version \"{}\")\n",
        env!("CARGO_PKG_VERSION")
    ));
    out.push_str(&format!("  (uuid \"{sheet_uuid}\")\n"));
    out.push_str("  (paper \"A3\")\n");
    out.push_str("  (title_block\n");
    out.push_str(&format!("    (title \"{}\")\n", escape(board.name())));
    out.push_str("    (comment 1 \"Generated by via; schematic-first review artifact\")\n");
    out.push_str("  )\n");
    out.push_str("  (lib_symbols\n");
    for template in templates.values() {
        out.push_str(&render_symbol_template(
            template,
            Some(&options.symbol_library_name),
        ));
    }
    out.push_str("  )\n");

    for module in placed {
        out.push_str(&render_symbol_instance(module, options));
        for pin in &module.pins {
            out.push_str(&render_pin_connection(module, pin, pin_nets));
        }
    }

    out.push_str("  (sheet_instances\n");
    out.push_str("    (path \"/\" (page \"1\"))\n");
    out.push_str("  )\n");
    out.push_str(")\n");
    out
}

pub(super) fn render_symbol_library(templates: &BTreeMap<String, SymbolTemplate>) -> String {
    let mut out = String::new();
    out.push_str("(kicad_symbol_lib\n");
    out.push_str(&format!("  (version {SYMBOL_LIB_VERSION})\n"));
    out.push_str(&format!("  (generator \"{GENERATOR}\")\n"));
    for template in templates.values() {
        out.push_str(&render_symbol_template(template, None));
    }
    out.push_str(")\n");
    out
}

fn render_symbol_template(template: &SymbolTemplate, library: Option<&str>) -> String {
    let lib_name = match library {
        Some(library) => format!("{}:{}", sanitize_symbol(library), template.name),
        None => template.name.clone(),
    };
    let mut out = String::new();
    let top = template.half_height;
    let bottom = -template.half_height;

    out.push_str(&format!(
        "    (symbol \"{}\" (pin_numbers hide) (pin_names (offset 1.016)) (exclude_from_sim no) (in_bom yes) (on_board yes) (duplicate_pin_numbers_are_jumpers no)\n",
        escape(&lib_name)
    ));
    out.push_str(&format!(
        "      (property \"Reference\" \"U\" (at 0 {} 0) (effects (font (size 1.27 1.27))))\n",
        fmt_num(top + 3.0)
    ));
    out.push_str(&format!(
        "      (property \"Value\" \"{}\" (at 0 {} 0) (hide yes) (effects (font (size 1.27 1.27))))\n",
        escape(&template.name),
        fmt_num(bottom - 3.0)
    ));
    out.push_str("      (property \"Footprint\" \"\" (at 0 0 0) (hide yes) (effects (font (size 1.27 1.27))))\n");
    out.push_str("      (property \"Datasheet\" \"\" (at 0 0 0) (hide yes) (effects (font (size 1.27 1.27))))\n");
    out.push_str("      (property \"Description\" \"\" (at 0 0 0) (hide yes) (effects (font (size 1.27 1.27))))\n");
    out.push_str(&format!(
        "      (symbol \"{}_0_1\"\n",
        escape(&template.name)
    ));
    out.push_str(&format!(
        "        (rectangle (start {} {}) (end {} {}) (stroke (width 0.254) (type default)) (fill (type background)))\n",
        fmt_num(-BODY_HALF_WIDTH),
        fmt_num(top),
        fmt_num(BODY_HALF_WIDTH),
        fmt_num(bottom)
    ));
    for pin in &template.pins {
        out.push_str(&format!(
            "        (pin passive line (at {} {} {}) (length {}) (name \"{}\" (effects (font (size 1 1)))) (number \"{}\" (effects (font (size 1 1)))))\n",
            fmt_num(pin.x),
            fmt_num(pin.y),
            pin.rotation,
            fmt_num(PIN_LENGTH),
            escape(&pin.name),
            escape(&pin.number)
        ));
    }
    out.push_str("      )\n");
    out.push_str("    )\n");
    out
}

fn render_symbol_instance(module: &PlacedModule, options: &SchematicProjectOptions) -> String {
    let symbol_uuid = stable_uuid(&format!("symbol:{}:{}", module.refdes, module.value));
    let lib_id = format!(
        "{}:{}",
        sanitize_symbol(&options.symbol_library_name),
        module.symbol_name
    );
    let footprint = module
        .footprint
        .as_ref()
        .map(|name| match &options.footprint_library_name {
            Some(lib) => format!("{}:{name}", sanitize_symbol(lib)),
            None => name.clone(),
        })
        .unwrap_or_default();
    let top = module.y - module.half_height - 3.0;
    let bottom = module.y + module.half_height + 3.0;
    let mut out = String::new();

    out.push_str(&format!(
        "  (symbol (lib_id \"{}\") (at {} {} 0) (unit 1)\n",
        escape(&lib_id),
        fmt_num(module.x),
        fmt_num(module.y)
    ));
    out.push_str("    (exclude_from_sim no) (in_bom yes) (on_board yes) (dnp no)\n");
    out.push_str(&format!("    (uuid \"{symbol_uuid}\")\n"));
    out.push_str(&format!(
        "    (property \"Reference\" \"{}\" (at {} {} 0) (effects (font (size 1.27 1.27))))\n",
        escape(&module.refdes),
        fmt_num(module.x),
        fmt_num(top)
    ));
    out.push_str(&format!(
        "    (property \"Value\" \"{}\" (at {} {} 0) (hide yes) (effects (font (size 1.27 1.27))))\n",
        escape(&module.value),
        fmt_num(module.x),
        fmt_num(bottom)
    ));
    out.push_str(&format!(
        "    (property \"Footprint\" \"{}\" (at {} {} 0) (hide yes) (effects (font (size 1.27 1.27))))\n",
        escape(&footprint),
        fmt_num(module.x),
        fmt_num(bottom + 3.0)
    ));
    out.push_str(&format!(
        "    (property \"Datasheet\" \"\" (at {} {} 0) (hide yes) (effects (font (size 1.27 1.27))))\n",
        fmt_num(module.x),
        fmt_num(bottom + 6.0)
    ));
    out.push_str(&format!(
        "    (property \"Description\" \"\" (at {} {} 0) (hide yes) (effects (font (size 1.27 1.27))))\n",
        fmt_num(module.x),
        fmt_num(bottom + 9.0)
    ));

    for pin in &module.pins {
        let pin_uuid = stable_uuid(&format!("pin:{}:{}", module.refdes, pin.number));
        out.push_str(&format!(
            "    (pin \"{}\" (uuid \"{}\"))\n",
            escape(&pin.number),
            pin_uuid
        ));
    }

    out.push_str("    (instances\n");
    out.push_str("      (project \"\"\n");
    out.push_str(&format!(
        "        (path \"/{}\"\n",
        stable_uuid(&format!("sheet:instance:{}", module.refdes))
    ));
    out.push_str(&format!(
        "          (reference \"{}\")\n",
        escape(&module.refdes)
    ));
    out.push_str("          (unit 1)\n");
    out.push_str("        )\n");
    out.push_str("      )\n");
    out.push_str("    )\n");
    out.push_str("  )\n");
    out
}

pub(super) fn render_pin_connection(
    module: &PlacedModule,
    pin: &SymbolPin,
    pin_nets: &BTreeMap<(String, String), String>,
) -> String {
    let x0 = module.x + pin.x;
    let y = module.y - pin.y;
    let Some(net_name) = pin_nets.get(&(module.refdes.clone(), pin.logical_pin.clone())) else {
        return format!(
            "  (no_connect (at {} {}) (uuid \"{}\"))\n",
            fmt_num(x0),
            fmt_num(y),
            stable_uuid(&format!("noconnect:{}:{}", module.refdes, pin.number))
        );
    };
    let (x1, y1, label_x, label_y, label_rot, justify) = match pin.side {
        SymbolSide::Left => (x0 - LABEL_STUB, y, x0 - LABEL_STUB, y, 180, "right"),
        SymbolSide::Right => (x0 + LABEL_STUB, y, x0 + LABEL_STUB, y, 0, "left"),
        SymbolSide::Top => (x0, y - LABEL_STUB, x0, y - LABEL_STUB, 90, "left"),
        SymbolSide::Bottom => (x0, y + LABEL_STUB, x0, y + LABEL_STUB, 270, "left"),
    };

    format!(
        "  (wire (pts (xy {} {}) (xy {} {})) (stroke (width 0) (type default)) (uuid \"{}\"))\n  (label \"{}\" (at {} {} {}) (effects (font (size 1.27 1.27)) (justify {})) (uuid \"{}\"))\n",
        fmt_num(x0),
        fmt_num(y),
        fmt_num(x1),
        fmt_num(y1),
        stable_uuid(&format!(
            "wire:{}:{}:{}",
            module.refdes, pin.number, net_name
        )),
        escape(net_name),
        fmt_num(label_x),
        fmt_num(label_y),
        label_rot,
        justify,
        stable_uuid(&format!(
            "label:{}:{}:{}",
            module.refdes, pin.number, net_name
        ))
    )
}

pub(super) fn render_project_file(board: &Board, stem: &str) -> String {
    let rules = board.rules();
    format!(
        r#"{{
  "board": {{
    "design_settings": {{
      "defaults": {{
        "board_outline_line_width": 0.1,
        "copper_line_width": {},
        "silk_line_width": 0.15,
        "silk_text_size_h": 1.0,
        "silk_text_size_v": 1.0
      }},
      "rules": {{
        "min_clearance": {},
        "min_copper_edge_clearance": 0.25,
        "min_hole_clearance": 0.25,
        "min_track_width": {}
      }}
    }}
  }},
  "meta": {{
    "filename": "{stem}.kicad_pro",
    "version": 1
  }},
  "project": {{
    "files": []
  }}
}}
"#,
        fmt_num(rules.default_track_width_mm()),
        fmt_num(rules.clearance_mm()),
        fmt_num(rules.default_track_width_mm()),
    )
}

pub(super) fn render_sym_lib_table(
    options: &SchematicProjectOptions,
    symbol_library_file: &str,
) -> String {
    format!(
        "(sym_lib_table\n  (lib (name \"{}\") (type \"KiCad\") (uri \"${{KIPRJMOD}}/{}\") (options \"\") (descr \"Generated via symbols\"))\n)\n",
        escape(&sanitize_symbol(&options.symbol_library_name)),
        escape(symbol_library_file)
    )
}

pub(super) fn render_fp_lib_table(options: &SchematicProjectOptions) -> String {
    match (
        &options.footprint_library_name,
        &options.footprint_library_uri,
    ) {
        (Some(name), Some(uri)) => format!(
            "(fp_lib_table\n  (lib (name \"{}\") (type \"KiCad\") (uri \"{}\") (options \"\") (descr \"via footprint library\"))\n)\n",
            escape(&sanitize_symbol(name)),
            escape(uri)
        ),
        _ => "(fp_lib_table)\n".to_owned(),
    }
}
